repositories:
  bitcoin:
    - bitcoin
  bitcoin_cash:
#    - bchd
    - bitcoin-cash-node
#    - bitcoin-verde
  cardano:
    - cardano-node
  ethereum:
#    - besu
#    - erigon
    - go-ethereum
    - nethermind
#    - reth
  litecoin:
    - litecoin
  polkadot:
    - polkadot-sdk
  solana:
    - solana
  tezos:
    - tezos-mirror
  zcash:
    - zcash

metrics:
  - entropy
  - gini
  - hhi
  - nakamoto_coefficient
  - theil_index
  - max_power_ratio
  - total_entities

# A list of the granularities to be used in the analysis. It corresponds to the number of commits that will be
#  included in each sample window.
# If empty, then the entire history of the repository will be considered as a single sample window.
granularities:
  -
  - 100
  - 250
  - 500
  - 1000

entity_types:
  - author
  - committer

weight_types:
  - number_of_commits
  - lines_added
  - lines_deleted
  - total_lines
