repositories:
  bitcoin:
    - bitcoin
  bitcoin_cash:
#    - bchd
    - bitcoin-cash-node
#    - bitcoin-verde
  cardano:
    - cardano-node
  ethereum:
#    - besu
#    - erigon
    - go-ethereum
    - nethermind
#    - reth
  litecoin:
    - litecoin
  polkadot:
    - polkadot-sdk
  solana:
    - solana
  tezos:
    - tezos-mirror
  zcash:
    - zcash

metrics:
  - entropy
#  - gini
  - herfindahl_hirschman_index
#  - nakamoto_coefficient
  - max_power_ratio
  - total_contributors
  - theil_index

# The number of commits that will be included in each sample window.
# If empty, then the entire history of the repository will be considered as a single sample window.
commits_per_sample_window:
  -
  - 100
  - 250
  - 500
  - 1000

contributor_types:
  - author
  - committer

# A list of the weights to be used in the analysis. The options are:
# commits, merge_commits, lines_changed, lines_added, lines_deleted
contribution_types:
  - commits
  - merge_commits
  - lines_changed
#  - lines_added
#  - lines_deleted


# Flag to indicate if new commit data should be pulled from the repositories.
# Note that this is only relevant for some repository if it already exists locally.
# If a repository does not exist locally, then it will be cloned and commit data will be pulled regardless of this flag.
refresh_data: false